changelog:
  categories:
    - title: "New Features"
      labels: ["type: feature"]
    - title: "Bug Fixes"
      labels: ["type: bug"]
    - title: "Improvements"
      labels: ["type: refactor"]
    - title: "Documentation"
      labels: ["type: docs"]
    - title: "Maintenance"
      labels: ["type: chore", "type: security", "type: test"]
    - title: "Other Changes"
      labels: ["*"]
  exclude:
    labels: ["duplicate", "invalid", "wontfix"]
